= README
:toc:

This is a conversion of the popular https://github.com/jekyll/minima[minima] theme for Jekyll to primarily use AsciiDoc source files (instead of Markdown).

It uses the https://github.com/asciidoctor/jekyll-asciidoc[Jekyll AsciiDoc Plugin].

If you find more things where the minima code has to be expanded to cover Asciidoctor output, please submit an issue or pull request here.

== Tasks
* [x] Convert the markdown files to ´adoc´
* [x] Add syntax highlighting
* [x] Integrate the table of content created by AsciiDoc in the sidebar for posts (if there is enough space)

== Making passthrough blocks work
To process liquid templates (e.g. `{% include my-themes-great-include.html %}`) inside asciidoc files / passthrough-blocks, you need to have `:page-liquid:` in the header

== Source code highlighting
The default way to do source code highlighting in Jekyll is by using Rouge (instead of pygments)
You can add highlighting into a page by simply setting `:page-liquid:` at the top of the correct asciidoc page.
The `scss` already contains definitions for the colors.

== Sidebar Table of Contents
This theme can integrate the table of contents that can be generated with asciidoc in a sidebar.
When there is enough space on the left side, a sidebar with the table of contents will be displayed.
If there is not enough space on the side, it will be moved under the page title.

To use this feature in a page, set the following two attributes to true:
- `:toc:`
- `:page-toc:`

== CI with GitHub actions
AsciiDoc files cannot directly be published by GitHub pages because the Jekyll plugin `jekyll-asciidoc` is https://webapps.stackexchange.com/questions/114606/can-github-pages-render-asciidoc[not whitelisted].

To publish to GitHub pages, Jekyll must render the HTML pages otherwise.
One way is to use GitHub's own continuous integration platform GitHub pages.
The workflow in the `.github` directory of this repository demonstrates how this can be done.
When using this workflow, make sure that you have a `gh-pages` branch.
Also make sure that to also push the `Gemfile.lock` file to the source repository (can be created via `bundle install`).
Here the list of operating systems in the `PLATFORMS` section of `Gemfile.lock` must contain the OS which is used for deployment (here `x86_64-linux`).
